project:
  name: example
  deployable_in_heroku: True
  apps:
    - name: account
      models:
        - name: User
          str:
            - name
            - surname
          fields:
            - name:
              - char
              - notnull
            - email:
              - email
              - unique
              - notnull
            - surname:
              - char
              - notnull
            - age:
              - int
            - created_at:
              - datetime
              - auto_now_add
            - last_login:
              - datetime
              - auto_now
        - name: Admin
          str:
            - user
            - access_level
          fields:
            - user:
              - foreign
              - notnull
            - rights:
              - char
            - access_level:
              - int
              - notnull
    - name: location
      models:
        - name: City
          str:
          - name
          - country
          fields:
            - name:
              - char
              - unique
              - notnull
            - population:
              - int
              - notnull
            - country:
              - char
              - notnull
        - name: Campus
          str:
          - name
          - city
          fields:
            - name:
              - char
              - unique
              - notnull
            - rating:
              - char
            - city:
              - foreign
              - notnull
        - name: Room
          str:
          - name
          - campus
          fields:
            - name:
              - char
              - unique
              - notnull
            - floor:
              - int
              - notnull
            - campus:
              - foreign
              - notnull