project:
  name: example
  apps:
    - name: account
      models:
        - name: Member
          str:
            - access_level
            - created_at
          fields:
            - user:
              - foreign
              - notnull
            - access_level:
              - int
              - notnull
            - created_at:
              - datetime
              - auto_now_add
    - name: location
      models:
        - name: City
          str:
          - name
          - country
          fields:
            - name:
              - char
              - unique
              - notnull
            - population:
              - int
              - notnull
            - country:
              - char
              - notnull
        - name: Campus
          str:
          - name
          - city
          fields:
            - name:
              - char
              - unique
              - notnull
            - rating:
              - char
            - city:
              - foreign
              - notnull