project:
  name: example
  apps:
    - name: account
      models:
        - name: User
          str:
            - name
            - surname
          fields:
            - name:
              - char
            - email:
              - email
              - unique
            - surname:
              - char
            - age:
              - int
            - created_at:
              - datetime
            - last_login:
              - datetime
        - name: Admin
          str:
            - name
            - surname
          fields:
            - user:
              - foreign
            - rights:
              - char
            - access_level:
              - int
    - name: location
      models:
        - name: City
          str:
          - name
          - country
          fields:
            - name:
              - char
              - unique
            - population:
              - int
            - country:
              - char
        - name: Campus
          str:
          - name
          - city
          fields:
            - name:
              - char
              - unique
            - rating:
              - char
            - city:
              - foreign
        - name: Room
          str:
          - name
          - campus
          fields:
            - name:
              - char
              - unique
            - floor:
              - int
            - campus:
              - foreign